---
ntp:
  - server: 2.2.2.2

eigrp:
  name: "IPvZero"
  as: "55"
  rid: 3.3.3.3
  type: "SPOKE"
  networks:
    - number: 172.16.1.0
      wildcard: 0.0.0.255
    - number: 10.3.3.0
      wildcard: 0.0.0.255

nhrp:
  tunnel_int: "0"
  tunnel_ip: 172.16.1.2
  tunnel_mask: 255.255.255.0
  hub:
    tun_ip: 172.16.1.1
    global_ip: 202.0.0.1
  tunnel_id: "5"
  tunnel_source: "GigabitEthernet2"
